### ISSUE TITLE
task tp::test fails, but local OS command runs fine

### ISSUE THREAD

**Issue by florusb** [example42/puppet-tp#101]
## Expected Behavior

That the task tp::test runs the tp test successfully. I use them also in a CD4PE job.

## Actual Behavior

The task fails with:

Error: Finished with exit code 1
[31mtct-admin-vm01 -  - custom: /etc/tp/test/ FAIL[0m

[31mSome test in ERROR[0m

This happens on all node in this test enviroment.

## Steps to Reproduce the Problem

Run tp::test task

However if I run on the OS directly:
root@tct-deploy:~# tp test
tct-deploy - supervisor - package: supervisor OK
tct-deploy - supervisor - service: supervisor OK
tct-deploy - rsyslog - package: rsyslog OK
tct-deploy - rsyslog - service: rsyslog OK
tct-deploy - lsof - package: lsof OK
tct-deploy - iptraf - package: iptraf-ng OK
tct-deploy - openssh - package: openssh-server OK
tct-deploy - openssh - service: ssh OK
tct-deploy - multitail - package: multitail OK
tct-deploy - insightagent - custom: /etc/tp/test/insightagent OK
tct-deploy - insightagent - service: ir_agent OK
tct-deploy - bind-utils - package: dnsutils OK
tct-deploy - screen - package: screen OK
tct-deploy - htop - package: htop OK
tct-deploy - psmisc - package: psmisc OK
tct-deploy - base - custom: /etc/tp/test/base OK

All tests OK

## Specifications

Please add this info:

1.  Output of `facter -p` on the failing node (at least the OS related facts)
2.  Version of Puppet and of the module
Latest Puppet Enterprise version (2021.7.1) and I get tp directly from the master branch
4.  The relevant Puppet code and eventually Hiera data

**Comment by alvagante** [comment]
merged fixing mr
