### ISSUE TITLE
Syntax error at 'Variant'

### ISSUE THREAD

**Issue by amateo** [example42/puppet-tp#20]
I'm trying to use tp module, version 1.0.0, with puppet 3 (3.8.6).
When I try to use it, I get the error 

> Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Syntax error at 'Variant'; expected ')' at /puppet/environments/feature_TLM_3240/modules/tp/manifests/install.pp:76 on node canis30.um.es

Is the module compatible with puppet 3.8? Or is it another reason for the fail?

**Comment by alvagante** [comment]
tp::install is compatible with Puppet 4 only Use tp::install3 with Puppet 3 (same applies for the other defines, On Puppet 3 use the ones with 3 suffix)

**Comment by amateo** [comment]
Oh... Thank you.
