### ISSUE TITLE
module path does not exist

### ISSUE THREAD

**Issue by logicminds** [example42/puppet-tp#37]
## Expected Behavior 
`tp list` would return a list of packages

## Actual Behavior

```
root@73f7186c66f8:/# tp list
/usr/local/bin/tp:106:in `open': No such file or directory @ dir_initialize - /etc/puppetlabs/code/environments/production/modules/tinydata/data (Errno::ENOENT)
	from /usr/local/bin/tp:106:in `entries'
	from /usr/local/bin/tp:106:in `<main>'
```
## Steps to Reproduce the Problem

1. docker run -ti ruby:2.3.1 bash
2. gem install puppet
3. mkdir -p /opt/puppetlabs/bin
4. ln -nfs /usr/local/bin/ruby /opt/puppetlabs/bin/ruby
5. puppet module install example42-tp
6. puppet tp setup
7. tp list

## The problem
Tp sets the data source to `/etc/puppetlabs/code/environments/production/modules`
However, puppet is using `/etc/puppetlabs/code/modules` by default.

I suspect this is because when the module was installed there was no configured environmentpath in the settings.

I think TP should be looking in basemodulepath and environment path

**Comment by alvagante** [comment]
Just for clarity, step 5 for "puppet tp install" right?

**Comment by logicminds** [comment]
yes step 5 is `puppet tp install`

**Comment by logicminds** [comment]
updated original instructions.

**Comment by alvagante** [comment]
Version 1.4.2 (also on the forge) fixes this, even if it's not an optimal solution (but I slightly prefer this that to run Puppet each time tp list is run just to get the correct paths from config)
