### ISSUE TITLE
metadata.json os missing  "data_provider" entry

### ISSUE THREAD

**Issue by snesbittsea** [example42/puppet-tp#39]
## Expected Behavior 
TP module should implement the module data in hiera

## Actual Behavior
TP module is not processing data/common.yaml

## Steps to Reproduce the Problem

  1.Unit test run on psick profile module fails with undefined TP variables

Fix is to add line to metadata.json: "data_provider": "hiera"

**Comment by alvagante** [comment]
With version 2.x, just released, i decided to go back to good old params pattern.
If we want to keep compatibility for Puppet > 4.4 data in modules is not an option (due to madness with hiera.yaml versions). The main tp class anyway, is not required, and is used only if cli command is enabled.
