### ISSUE TITLE
install_hash?

### ISSUE THREAD

**Issue by Ac0lyte** [example42/puppet-tp#4]
Under the **Usage with Hiera** section in the README.md  it shows an example using **tp::install_hash**. I suspect that this should be **tp::settings_hash**.
- Tim

**Comment by alvagante** [comment]
Yeah, good catch, PR welcomed

**Comment by alvagante** [comment]
Actually what's there is correct, but probably not clear.
The examples are for parameters of the class tp , which declares different tp defines.
