### ISSUE TITLE
epp templates fail in tp::conf 

### ISSUE THREAD

**Issue by alvagante** [example42/puppet-tp#85]

**Comment by florusboth** [comment]
Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, epp() can only be called using the 4.x function API. See Scope#call_function (file: /etc/puppetlabs/code/environments/host/modules/tp/manifests/conf.pp, line: 279, column: 21) (file: /etc/puppetlabs/code/environments/host/site/profile/manifests/app/openssh.pp, line: 115) on node celery.vagrant.tricentsecurity.net
