### ISSUE TITLE
remove warning for tests only

### ISSUE THREAD

**Issue by florusboth** [example42/puppet-tp#88]
## Actual Behavior

Warning: Scope(Tp::Test[base]): No tinydata found for: base in /etc/puppetlabs/code/environments/host/modules/tinydata/data/base/hiera.yaml. Trying to install package base
Warning: Undefined variable 'upstream_repo';
   (file & line not available)
Warning: Undefined variable 'repo';
   (file & line not available)
## Steps to Reproduce the Problem

  1. 
  1. 
  1. 

## Specifications

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)
  1. Version of Puppet and of the module
  1. The relevant Puppet code and eventually Hiera data

**Comment by alvagante** [comment]
fixed in a recent release
